// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAviUUmkp-puaVoSW31mmSu4znKea0XaPA',
    appId: '1:845217057886:web:22d0b0065833df978638cf',
    messagingSenderId: '845217057886',
    projectId: 'e-commerce-ad710',
    authDomain: 'e-commerce-ad710.firebaseapp.com',
    storageBucket: 'e-commerce-ad710.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6YNbLN_cV_6yz86JDKgCm0Ex8n6DZ4y0',
    appId: '1:845217057886:android:9f2053a7d84821ac8638cf',
    messagingSenderId: '845217057886',
    projectId: 'e-commerce-ad710',
    storageBucket: 'e-commerce-ad710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGePwwJ84bHqrBaqR0Cezgkfn9Eqi3uKA',
    appId: '1:845217057886:ios:3831e1e5f2c112988638cf',
    messagingSenderId: '845217057886',
    projectId: 'e-commerce-ad710',
    storageBucket: 'e-commerce-ad710.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
